# Generated by Django 6.0.7 on 2026-08-28 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('question_text', models.TextField()),
                ('difficulty', models.CharField(choices=[('EASY', 'Beginner / Fundamental'), ('MEDIUM', 'Intermediate / Standard'), ('HARD', 'Advanced / Olympiad')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('SOLVED', 'Solved'), ('PENDING', 'Pending Review'), ('AI_GENERATED', 'AI / Heuristic Resolved')], default='SOLVED', max_length=20)),
                ('student_name', models.CharField(default='Anonymous Student', max_length=100)),
                ('views_count', models.IntegerField(default=0)),
                ('upvotes', models.IntegerField(default=0)),
                ('latex_formula', models.TextField(blank=True, help_text='Optional LaTeX math expression associated with doubt')),
                ('code_snippet', models.TextField(blank=True, help_text='Optional code snippet for CS doubts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(default='book', max_length=50)),
                ('color_hex', models.CharField(default='#3B82F6', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoubtFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doubt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='doubts.doubt')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('step_title', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('formula_used', models.TextField(blank=True)),
                ('diagram_type', models.CharField(blank=True, max_length=50)),
                ('code_execution_output', models.TextField(blank=True)),
                ('doubt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='doubts.doubt')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.AddField(
            model_name='doubt',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubts', to='doubts.subject'),
        ),
        migrations.CreateModel(
            name='TopicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='doubts.subject')),
            ],
            options={
                'verbose_name_plural': 'Topic Categories',
            },
        ),
        migrations.AddField(
            model_name='doubt',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doubts', to='doubts.topiccategory'),
        ),
    ]
