version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=educlear_backend.settings
      - DEBUG=1
    volumes:
      - .:/app
    command: python main.py
