# Generated by Django 6.0.7 on 2026-08-28 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doubts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author_name', models.CharField(default='Peer / Educator', max_length=100)),
                ('is_accepted', models.BooleanField(default=False)),
                ('upvotes', models.IntegerField(default=0)),
                ('latex_support', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Student', max_length=100)),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.forumanswer')),
            ],
        ),
        migrations.CreateModel(
            name='ForumQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author_name', models.CharField(default='Student', max_length=100)),
                ('tags', models.CharField(help_text='Comma-separated tags e.g. calculus, limits, derivatives', max_length=200)),
                ('upvotes', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('is_solved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_questions', to='doubts.subject')),
            ],
        ),
        migrations.AddField(
            model_name='forumanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forum.forumquestion'),
        ),
    ]
